#cloud-config

manage_etc_hosts: localhost

runcmd:
  - kubeadm join --token ${kube-token} --discovery-token-unsafe-skip-ca-verification ${master-ip}:6443

final_message: "Kubernetes worker is ready to use"
