#cloud-config

manage_etc_hosts: localhost

write_files:
  - content: |
      apiVersion: kubeadm.k8s.io/v1alpha1
      kind: MasterConfiguration
      api:
        advertiseAddress: ens3
      etcd:
        endpoints:
        - 0.etcd-server.service.automium.consul
        - 1.etcd-server.service.automium.consul
        - 2.etcd-server.service.automium.consul
      token: ${kube-token}
      tokenTTL: 0
      apiServerCertSANs:
      - ${public-ip}
    path: /root/kubeadm-config.yml
    permission: 0600

runcmd:
  - sudo kubeadm init --config /root/kubeadm-config.yml
  - sudo rm /root/kubeadm-config.yml
  - sudo mkdir -p /root/.kube
  - sudo cp /etc/kubernetes/admin.conf /root/.kube/config
  - sudo chown root:root /root/.kube/config
  - sudo sysctl -w net.bridge.bridge-nf-call-iptables=1
  - sudo kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"
  - sync

final_message: "Kubernetes master is ready to use"

